version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: captcha_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./api-captcha/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - captcha-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - captcha-network

  api:
    build: ./api-captcha
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=captcha_db
    networks:
      - captcha-network

  frontend:
    build: ./app-captcha
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - captcha-network

  captcha-solver:
    build: ./Python  # 📌 Dossier contenant le Dockerfile Python
    container_name: captcha-solver-container
    ports:
      - "8000:8000"  # 📌 Exposition du port pour FastAPI
    depends_on:
      - api  # 📌 S'assure que l'API est lancée avant le solver
    networks:
      - captcha-network

volumes:
  mysql_data:

networks:
  captcha-network:
    driver: bridge
