version: '3.8'

services:
  captcha-solver:
    build: .
    container_name: captcha-solver-container
    ports:
      - "8000:8000"
    networks:
      - captcha-network

networks:
  captcha-network:
    driver: bridge
